apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - ingress.yaml

secretGenerator:
  - name: postgres-secret
    envs:
      - secrets/postgres.env
  - name: app-secret
    envs:
      - secrets/app.env 